import {checarAutenticacao,obterUsuarioLogado} from '../utilitarios/auth.js';
import {getProdutos,postEntradaEstoque,postSaidaEstoque,postDevolucao,postAjuste} from '../api/services.js';
import {apiFetch} from '../api/client.js';
import {formatarData} from '../utilitarios/formatters.js';
if(!checarAutenticacao()) throw new Error('Não autenticado');
const produtos=(await getProdutos()).dados||[];
const $=id=>document.getElementById(id);
function preencherProdutos(id){const s=$(id);s.innerHTML='<option value="">Selecione...</option>'+produtos.map(p=>`<option value="${p.id}">${p.nome} — estoque: ${p.estoque_atual}</option>`).join('');}
['produto-entrada','produto-saida','produto-devolucao','produto-ajuste'].forEach(id=>{if($(id))preencherProdutos(id);});
function pSelecionado(id){return produtos.find(p=>p.id===Number($(id).value));}
function camposRastreio(prefix){const p=pSelecionado(`produto-${prefix}`);const box=$(`rastreio-${prefix}`);if(!box)return;box.innerHTML='';if(!p)return;const tipo=(p.tipo_rastreabilidade||'NENHUMA').toUpperCase();if(tipo==='BATERIA')box.innerHTML='<div class="form-row"><div class="form-group"><label>Número de série</label><input id="serie-entrada" required></div><div class="form-group"><label>Data de validade</label><input id="validade-entrada" type="date" required></div></div>';else if(tipo==='MOTOR_CONTROLADOR')box.innerHTML='<div class="form-row"><div class="form-group"><label>Número de série</label><input id="serie-entrada" required></div><div class="form-group"><label>Lote</label><input id="lote-entrada" required></div></div>';else if(tipo==='VEICULO')box.innerHTML='<div class="form-group"><label>ID único do veículo</label><input id="id-unico-entrada" required></div>';else if(tipo==='PECA_SEGURANCA')box.innerHTML='<div class="form-group"><label>Lote</label><input id="lote-entrada" required></div>';}
$('produto-entrada')?.addEventListener('change',()=>camposRastreio('entrada'));
function extrasComuns(prefix){return {tipo_transporte:$(`transporte-${prefix}`)?.value||'',montado_desmontado:$(`montagem-${prefix}`)?.value||'',localizacao:$(`localizacao-${prefix}`)?.value||'',observacao:$(`obs-${prefix}`)?.value||''};}
$('form-entrada')?.addEventListener('submit',async e=>{e.preventDefault();const p=pSelecionado('produto-entrada');const dados={produto_id:p.id,quantidade:Number($('qtd-entrada').value),fornecedor_id:Number($('fornecedor-entrada').value),numero_nota_fiscal:$('nf-entrada').value,numero_pedido_compra:$('pedido-entrada').value,...extrasComuns('entrada')};if($('serie-entrada'))dados.numero_serie=$('serie-entrada').value;if($('validade-entrada'))dados.data_validade=$('validade-entrada').value;if($('lote-entrada'))dados.lote=$('lote-entrada').value;if($('id-unico-entrada'))dados.identificador_unico=$('id-unico-entrada').value;await enviar(()=>postEntradaEstoque(dados),'Entrada registrada!','form-entrada');});
$('form-saida')?.addEventListener('submit',async e=>{e.preventDefault();const dados={produto_id:Number($('produto-saida').value),quantidade:Number($('qtd-saida').value),destinatario:$('destino-saida').value,motivo:$('motivo-saida').value,numero_pedido_venda:$('pedido-venda').value,...extrasComuns('saida')};await enviar(()=>postSaidaEstoque(dados),'Saída registrada!','form-saida');});
$('form-devolucao')?.addEventListener('submit',async e=>{e.preventDefault();const dados={produto_id:Number($('produto-devolucao').value),quantidade:Number($('qtd-devolucao').value),origem:$('origem-devolucao').value,motivo:$('motivo-devolucao').value,estado_produto:$('estado-devolucao').value,numero_pedido_venda:$('pedido-devolucao').value,reaproveitavel:$('reaproveitavel').checked,observacao:$('obs-devolucao').value};await enviar(()=>postDevolucao(dados),'Devolução registrada!','form-devolucao');});
$('form-ajuste')?.addEventListener('submit',async e=>{e.preventDefault();const dados={produto_id:Number($('produto-ajuste').value),nova_quantidade:Number($('nova-qtd').value),justificativa:$('justificativa').value};await enviar(()=>postAjuste(dados),'Ajuste realizado!','form-ajuste');});
async function enviar(fn,msg,form){try{await fn();alert(msg);$(form)?.reset();await carregarHistorico();location.reload();}catch(e){alert(e.message||'Erro na operação.');}}
async function carregarHistorico(){const r=await apiFetch('/api/v1/estoque/movimentacoes');const lista=r.dados||[];$('tbody-estoque').innerHTML=lista.map(m=>`<tr><td>${m.id}</td><td>${m.produto_nome||m.produto_id}</td><td>${m.tipo}</td><td>${m.quantidade}</td><td>${m.destinatario||'-'}</td><td>${m.motivo||'-'}</td><td>${formatarData(m.data_movimentacao)}</td></tr>`).join('')||'<tr><td colspan="7">Nenhuma movimentação.</td></tr>';}
async function carregarFornecedores(){try{const r=await apiFetch('/api/v1/fornecedores');$('fornecedor-entrada').innerHTML=(r.dados||[]).map(f=>`<option value="${f.id}">${f.nome}</option>`).join('');}catch{}}
const u=obterUsuarioLogado();if(u?.perfil!=='GERENTE')document.querySelector('#secao-ajuste')?.remove();carregarFornecedores();carregarHistorico();

$('btn-buscar-codigo')?.addEventListener('click',async()=>{const c=$('busca-codigo').value.trim();if(!c)return;try{const r=await apiFetch(`/api/v1/estoque/buscar-codigo/${encodeURIComponent(c)}`);const p=r.dados;$('resultado-codigo').innerHTML=`<div class="card"><strong>${p.nome}</strong><br>Código: ${p.codigo_interno}<br>Estoque: ${p.estoque_atual}<br>Localização: ${p.localizacao_deposito||'-'}</div>`;}catch(e){$('resultado-codigo').textContent=e.message;}});
